name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12.1"]
    services:
      sonarqube:
        image: sonarqube:10.6-community
        options: >
          --memory=2g  
          --cpus="2.0" 
        ports:
          - 9000:9000
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy opencv-python matplotlib tensorflow flask pylint pytest coverage
    - name: Wait for SonarQube to be ready
      run: |
        echo "Waiting for SonarQube to be ready..."
        for i in {1..30}; do
          if curl -s http://localhost:9000/api/system/health | grep '"status":"OK"'; then
            echo "SonarQube is up!"
            break
          fi
          echo "Waiting for SonarQube to start..."
          sleep 10
        done
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: http://localhost:9000
      with:
        args: |
          -Dsonar.projectKey=<your_project_key>
    - name: Linting
      run: |
        pylint $(git ls-files '*.py')
      continue-on-error: true
    - name: Training Model
      run: |
        python model_creation.py
    - name: Automated Testing
      run: |  
        coverage run -m pytest -v -s
